### PR TITLE
Hello Tom! Sorry for the delay. Can I get my temperature converter added to the master please? Thanks

### PR DESCRIPTION
**Pull request by gustadjev**

### CODE REVIEW

**Comment by tsteelematc** [comment]
Looks like you have merge conflicts. Can you resolve them as I demonstrated in the vids. Basically merge master into your PR branch locally, resolve conflicts, then push the changes to your PR branch. Let me know if you have questions.

**Comment by gustadjev** [comment]
Hi @tsteelematc! Merge conflicts have been resolved. Please take a look at it. Thanks!

**Comment by tsteelematc** [comment]
You didn't resolve the merge conflicts properly. Your component should show up below all the previously merged components... Right now it should show up below Takyra's...

Let me know if that makes sense or if you need some help fixing this PR branch up... It seems there was also an Angular update in your branch, and we wouldn't want that in the master branch either.

You may be better off cherry-picking your slack-n-tell commits into a new branch for a new PR... Again, let me know if you want some help!

image

**Comment by gustadjev** [comment]
Hi, @tsteelematc I've tried to create a new branch from ggbossou/week-07-slack-n-tell but it doesn't allow me. However, I've attempted again to fix the conflicts. 
I don't know how I could fix angular update issues. I've been notified of many vulnerabilities in my previous angular version, reason why I updated it.
May I have your assistance on how to fix this? Thanks!

**Comment by gustadjev** [comment]
Due to Angular version issues, this PR is closed, and a new one will be open

**Pull request closed without merging**
